"""empty message

Revision ID: 0b46bd4f7f44
Revises: 07bafba09312
Create Date: 2022-11-10 18:28:13.374260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b46bd4f7f44'
down_revision = '07bafba09312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_shows_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'shows_id')
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'venue_id')
    op.add_column('Artist', sa.Column('shows_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Artist_shows_id_fkey', 'Artist', 'Shows', ['shows_id'], ['id'])
    # ### end Alembic commands ###
